### ISSUE TITLE
JupyterLab 3 support using repo2docker / binder

### ISSUE THREAD

**Issue by aplamada** [krassowski/jupyterlab-lsp#503] opened 2021-02-04 08:44 UTC
`jupyterlab-lsp` is great and I am trying to use it with the new JupyterLab 3.

I tried to build a binder ready project (see below the configuration files) it looks like I still had to do in the postBuild
```shell
jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```

Is this as expected?

----

- `environment.yml` file:

```yaml
channels:
  - conda-forge

dependencies:
  - python >=3.6,<3.9.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - jupyter-offlinenotebook >=0.2
  - jupyterlab-lsp=3.3.0
  - jupyter-lsp-python=1.1.2
```

- `postBuild` file:
```shell
set -e

jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```

**Comment by jtpio** [comment] 2021-02-04 16:30
@aplamada could is be because the latest `jupyterlab-lsp` now defines the config file for Jupyter Server only?

https://github.com/krassowski/jupyterlab-lsp/blob/9c1778dd66354d9431756b7bc65d5fbbae665daf/python_packages/jupyter_lsp/setup.py#L15-L20

I think `repo2docker` / Binder still start a notebook server for now. So it probably means we would need to add the notebook server config `jupyter_notebook_config.py` to the data files to have the extension enabled by default on install.

**Comment by aplamada** [comment] 2021-02-04 18:06
Thanks! 
Unfortunately I don't have the know how but I can see something in this direction in other packages, e.g.:

https://github.com/dask/dask-labextension/blob/6afe2867dce574d7e7f8cb14d682c5dd5630a69a/setup.py#L43-L56 .

**Comment by bollwyvl** [comment] 2021-02-04 18:44
Can confirm this is required.

 "server extension" vs "serverextension", "ServerApp.jpserverextensions" vs
"NotebookApp.nbserverestensions". Probably just need to just support both,
sigh.

**Comment by krassowski** [comment] 2021-02-04 19:21
You are all right. I am sorry about this  annoyance.

I was aware that this might cause problems when porting to JupyterLab 3.0. To explain my reasoning:

- this is the default behaviour in [jupyterlab-cookicutter](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/%7B%7Bcookiecutter.python_name%7D%7D/__init__.py) so might affect other extensions too:
   - [nbdime](https://github.com/jupyter/nbdime/pull/551/files#diff-3374f7343c965824800a856b55e795490d64ed395ee5355fdc32d80130f9cb43R33) retained compatibility with notebook server
   - [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyterlab_git/__init__.py) did not
- I did not get much feedback when raising this upstream (whether [here](https://github.com/jupyterhub/jupyterhub/issues/3340) or [here](https://github.com/jupyterhub/jupyterhub/issues/3340) - granted, I was not too stark with my warnings about "hey this will cause issues"); an authoritative nod on what is the right way to proceed for extensions would be appreciated (@blink1073, @jasongrout: should we change our extension and the cookicutter or just push for roll out of `jupyter_server`?)
- I have a gut feeling that we will start having different problems if we start supporting `jupyter_notebook` as a server again; my point is: is it worth supporting two servers for now and then in 6 months time once everyone switches to `jupyter-server` have to deal with cryptic issues in cryptic bug reports filled by users who do not follow the issue template and do not provide sufficient information (and this is why in absence of arguments to contrary I went ahead with no support for `jupyter_notebook` as a server)

But as it seems to affect not only `jupyterhub` which is usually managed by advanced users, but `binder` too I am happy to reconsider.

Also, could https://github.com/jupyterlab/jupyterlab/pull/9681 help? It is a part of JupyterLab 3.0.6 and as far as I understand was intended to make `jupyterhub` use `jupyter_server` if available when running JupyterLab. @aplamada could you check which JupyterLab version you had this problem with? The 3.0.6 and 3.0.7 are fresh and might not have landed on conda-forge at the time you were installing (I'm hoping for that but probably not the case). Or maybe binder is using an older version of juypterhub that does not support this directive?

**Comment by krassowski** [comment] 2021-02-04 19:48
Having looked a bit more @jtpio seems to be an authority on this topic too (https://github.com/jupyterhub/repo2docker/pull/996) :)

Like really, I am happy with whichever you guys recommend you are more knowledgeable than me in the ecosystem. I was just missing some guidance when porting to 3.0.

**Comment by jtpio** [comment] 2021-02-05 08:43
> Unfortunately I don't have the know how but I can see something in this direction in other packages, e.g.:
> 
> https://github.com/dask/dask-labextension/blob/6afe2867dce574d7e7f8cb14d682c5dd5630a69a/setup.py#L43-L56 .

Probably that would be enough for now to enable the server extension for the classic notebook server?

> Having looked a bit more @jtpio seems to be an authority on this topic too ([jupyterhub/repo2docker#996](https://github.com/jupyterhub/repo2docker/pull/996)) :)

Right. Although this PR doesn't update the command used to start the server, which is probably going to stay `jupyter notebook --ip 0.0.0.0` for now so starting a classic notebook server.

However, it would be interesting to consider changing `repo2docker` to start `jupyter nbclassic` instead by default.  UI wise it wouldn't be a major change (still the Classic Notebook frontend) and hopefully be completely transparent to users. But it would run on Jupyter Server.

**Closed** 2021-02-06 21:50 UTC
