### ISSUE TITLE
Re-run of Azure pipelines fails due to pre-existing artifacts

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#103] opened 2019-11-16 18:28 UTC
It seems that artifacts from previous (failed) build conflict with the new ones, but I am not quite sure what is really happening here: https://dev.azure.com/krassowskimichal/jupyterlab-lsp/_build/results?buildId=150

![Screenshot from 2019-11-16 18-25-48](https://user-images.githubusercontent.com/5832902/68997481-d2a36500-089e-11ea-8eb8-89f545d65c39.png)

**Comment by bollwyvl** [comment] 2019-11-16 18:46
Yeah the issue is that the build number is not bumped for a re-run, and there's [no option](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) to overwrite an existing artifact. We need the artifacts between stages to have predictable names so that they can be restored to be recombined (and so that there are sane values when downloaded).

I usually just re-kick the whole run, by closing and re-opening the pull request, as it doesn't take that much longer (especially if it's a windows fail).

**Comment by bollwyvl** [comment] 2019-11-16 18:51
We could also investigate marking tests as being [flaky](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops)... which they are, as they are the full integration of (usually) windows, nodejs, python, notebook, the browser, jupyterlab, selenium, robot... it's really hard to anticipate what's going to fail at a particular time.

To that end, we could also just add a `RETRIES` settings in `atest` to the run tests a sane number of times (say 3).

**Comment by bollwyvl** [comment] 2019-11-16 19:19
https://github.com/krassowski/jupyterlab-lsp/pull/100/files#r347103929

**Comment by krassowski** [comment] 2020-01-07 16:33
I think it's better now, but it still happens:

![Screenshot from 2020-01-07 16-32-19](https://user-images.githubusercontent.com/5832902/71911312-655bd400-316b-11ea-81cc-5febf51cc24a.png)


https://dev.azure.com/krassowskimichal/jupyterlab-lsp/_build/results?buildId=262&view=results

**Comment by bollwyvl** [comment] 2020-01-07 18:34
Yeah, it's probably not fixable if we want the roll-up reports. It means
the tests failed three times, which is pretty gnarly flake.

We can get rid of the roll-up, which would shave a minute or two off the
build, but then you have to hunt around for the report you actually wanted
when there is a fail.

**Closed** 2021-02-01 12:57 UTC
