### ISSUE TITLE
How to configure LSP to disable aggressive auto-code-completion without confirming

### ISSUE THREAD

**Issue by txsing** [krassowski/jupyterlab-lsp#409] opened 2020-11-13 05:13 UTC
I suffered from LSP aggressively editing my code automatically without letting me confirm the changes.

**Comment by krassowski** [comment] 2020-11-13 09:01
Thank you for opening this issue. Unfortunately, I cannot help much without having the [bug report template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) filled in. It appears that you might have chosen a different template, or deleted it.

The template asks for information that we need in order to be able to help you. We know that this is a big ask, but this helps us diagnose issues quicker and gives us more time to improve this extension. If you have a problem filling it, please let us know and we will try to help (or improve the template if needed).

To be more specific, there is no auto-completion enabled in this extension. If you see any such behaviour, it is a bug and please help us fix it by providing a reproducible example (a gif also helps!). Moreover, the potentially problematic auto-hinting is disabled by default - again more details needed.

**Comment by krassowski** [comment] 2020-12-31 16:25
Hi @txsing, it's been over a month since you opened this issue but we have not heard from you on the details. Upon second inspection I think that you may have been using a way outdated version which had trigger character completion resulting in autocompletion, which was fixed upstream in JupyterLab 2.2. I will close this issue for now to reduce clutter, but please feel welcome to reopen it if you can provide details and reproduction instructions on the most recent version.

**Closed by krassowski** 2020-12-31 16:25 UTC
