### ISSUE TITLE
All functions are not working at all without any error message.

### ISSUE THREAD

**Issue by NMZ0429** [krassowski/jupyterlab-lsp#404] opened 2020-11-09 17:14 UTC
I have installed `jupyterlab-lsp`  following the instruction. 
However, lsp does not appear in status bar and none of its functions are not working. 
It's like lsp is completely not installed but its enabled according to extension manager. 

I have also checked it's enabled by
```
$ jupyter serverextension enable --sys-prefix --py jupyter_lsp
Enabling: jupyter_lsp
- Writing config: /Users/gen/.pyenv/versions/3.8.0/etc/jupyter
    - Validating...
      jupyter_lsp 0.9.2 OK
```

As I don't find any error message, I can not find out what to fix. What should I check?

**Comment by krassowski** [comment] 2020-11-09 17:56
Thank you for opening this issue :tulip:. I read it carefully but unfortunately, I cannot help much without having the [bug report template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) filled in. It appears that you might have chosen a different template, or deleted it.

The template asks for information that we need in order to be able to help you. We know that this is a big ask, but this helps us diagnose issues quicker and gives us more time to improve this extension. If you have a problem filling it, please let us know and we will try to help (or improve the template if needed).

With the information that you provided I can only assume it is a duplicate of #397 issue so I am going to close it for now. If it is not right, please use the right template to open a new issue. Thank you.

**Closed by krassowski** 2020-11-09 17:56 UTC
