### ISSUE TITLE
Error on startup on Linux no NPM installed at system level

### ISSUE THREAD

**Issue by IanQS** [krassowski/jupyterlab-lsp#181] opened 2020-01-26 01:58 UTC
## Description

Running 

```
conda activate X
jupyter lab
```

I see

```
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.485 LabApp] Failed to fetch commands from language server spec finder`dockerfile-language-server-nodejs`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.490 LabApp] Failed to fetch commands from language server spec finder`javascript-typescript-langserver`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.500 LabApp] Failed to fetch commands from language server spec finder`unified-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.505 LabApp] Failed to fetch commands from language server spec finder`vscode-css-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.510 LabApp] Failed to fetch commands from language server spec finder`vscode-html-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.514 LabApp] Failed to fetch commands from language server spec finder`vscode-json-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 17:39:00.520 LabApp] Failed to fetch commands from language server spec finder`yaml-language-server`:
    expected str, bytes or os.PathLike object, not tuple
```

I've seen [errors on startup issue #121](https://github.com/krassowski/jupyterlab-lsp/issues/121) which seems similar but I don't actually have npm at the system level. 

## Reproduce

On Manjaro Linux if that helps? 

```
conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab
conda activate jlab-test
pip install --pre jupyter-lsp
jupyter labextension install @krassowski/jupyterlab-lsp
conda install -c conda-forge nodejs
conda install -c conda-forge python-language-server r-languageserver
jupyter lab
```

## Expected behavior

Starts without errors for LSP

## Context

- Operating System and version: 5.4.13-3-MANJARO
- Browser and version: Firefox
- JupyterLab version: 1.2.6
- `jupyter-lsp` version: jupyter-lsp            0.7.0b0
- `@krassowski/jupyterlab-lsp` version: ?? (how do I check this?)

^ I ran `jupyter labextension update @krassowski/jupyterlab-lsp` and I received `No labextension named "@krassowski/jupyterlab-lsp" installed`?

<details><summary>Troubleshoot Output</summary>

```
$PATH:
	/home/ian/anaconda3/envs/jlab-test/bin
	/home/ian/anaconda3/bin
	/home/ian/.local/bin
	/home/ian/anaconda3/bin
	/home/ian/anaconda3/condabin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/sbin
	/opt/intel/mediasdk/bin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl
	/var/lib/snapd/snap/bin
	/home/ian/clion/bin
	/home/ian/pycharm/bin
	/home/ian/.antigen/bundles/robbyrussell/oh-my-zsh/lib
	/home/ian/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/wd
	/home/ian/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo
	/home/ian/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git
	/home/ian/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages
	/home/ian/.antigen/bundles/peterhurford/up.zsh
	/home/ian/.antigen/bundles/esc/conda-zsh-completion
	/home/ian/.antigen/bundles/zsh-users/zsh-syntax-highlighting
	/home/ian/clion/bin
	/home/ian/pycharm/bin

sys.path:
	/home/ian/anaconda3/envs/jlab-test/bin
	/home/ian/anaconda3/envs/jlab-test/lib/python38.zip
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8/lib-dynload
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8/site-packages

sys.executable:
	/home/ian/anaconda3/envs/jlab-test/bin/python

sys.version:
	3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:58:18) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.4.13-3-MANJARO-x86_64-with-glibc2.10

which -a jupyter:
	/home/ian/anaconda3/envs/jlab-test/bin/jupyter
	/home/ian/anaconda3/bin/jupyter
	/home/ian/anaconda3/bin/jupyter

pip list:
	Package                Version            
	---------------------- -------------------
	astroid                2.3.3              
	attrs                  19.3.0             
	autopep8               1.5                
	backcall               0.1.0              
	bleach                 3.1.0              
	certifi                2019.11.28         
	decorator              4.4.1              
	defusedxml             0.6.0              
	entrypoints            0.3                
	flake8                 3.7.9              
	future                 0.18.2             
	importlib-metadata     1.4.0              
	ipykernel              5.1.3              
	ipython                7.11.1             
	ipython-genutils       0.2.0              
	isort                  4.3.21             
	jedi                   0.15.2             
	Jinja2                 2.10.3             
	json5                  0.8.5              
	jsonschema             3.2.0              
	jupyter-client         5.3.4              
	jupyter-core           4.6.1              
	jupyter-lsp            0.7.0b0            
	jupyterlab             1.2.6              
	jupyterlab-server      1.0.6              
	lazy-object-proxy      1.4.3              
	MarkupSafe             1.1.1              
	mccabe                 0.6.1              
	mistune                0.8.4              
	more-itertools         8.1.0              
	nbconvert              5.6.1              
	nbformat               5.0.4              
	notebook               6.0.3              
	pandocfilters          1.4.2              
	parso                  0.5.2              
	pexpect                4.8.0              
	pickleshare            0.7.5              
	pip                    20.0.2             
	pluggy                 0.13.1             
	prometheus-client      0.7.1              
	prompt-toolkit         3.0.2              
	ptyprocess             0.6.0              
	pycodestyle            2.5.0              
	pydocstyle             5.0.2              
	pyflakes               2.1.1              
	Pygments               2.5.2              
	pylint                 2.4.4              
	pyrsistent             0.15.7             
	python-dateutil        2.8.1              
	python-jsonrpc-server  0.3.4              
	python-language-server 0.31.7             
	pyzmq                  18.1.1             
	rope                   0.16.0             
	Send2Trash             1.5.0              
	setuptools             45.1.0.post20200119
	six                    1.14.0             
	snowballstemmer        2.0.0              
	terminado              0.8.3              
	testpath               0.4.4              
	tornado                6.0.3              
	traitlets              4.3.3              
	ujson                  1.35               
	wcwidth                0.1.8              
	webencodings           0.5.1              
	wheel                  0.33.6             
	wrapt                  1.11.2             
	yapf                   0.29.0             
	zipp                   2.0.0

conda list:
	# packages in environment at /home/ian/anaconda3/envs/jlab-test:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       0_gnu    conda-forge
	_r-mutex                  1.0.1               anacondar_1    conda-forge
	astroid                   2.3.3                    py38_1    conda-forge
	attrs                     19.3.0                     py_0    conda-forge
	autopep8                  1.5                        py_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	binutils_impl_linux-64    2.33.1               he1b5a44_7    conda-forge
	binutils_linux-64         2.33.1              h9595d00_16    conda-forge
	bleach                    3.1.0                      py_0    conda-forge
	bwidget                   1.9.14                        0    conda-forge
	bzip2                     1.0.8                h516909a_2    conda-forge
	ca-certificates           2019.11.28           hecc5488_0    conda-forge
	cairo                     1.16.0            hfb77d84_1002    conda-forge
	certifi                   2019.11.28               py38_0    conda-forge
	curl                      7.65.3               hf8cf82a_0    conda-forge
	decorator                 4.4.1                      py_0    conda-forge
	defusedxml                0.6.0                      py_0    conda-forge
	entrypoints               0.3                   py38_1000    conda-forge
	flake8                    3.7.9                    py38_0    conda-forge
	fontconfig                2.13.1            h86ecdb6_1001    conda-forge
	freetype                  2.10.0               he983fc9_1    conda-forge
	fribidi                   1.0.5             h516909a_1002    conda-forge
	future                    0.18.2                   py38_0    conda-forge
	gcc_impl_linux-64         7.3.0                hd420e75_4    conda-forge
	gcc_linux-64              7.3.0               h553295d_16    conda-forge
	gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
	gfortran_impl_linux-64    7.3.0                hdf63c60_4    conda-forge
	gfortran_linux-64         7.3.0               h553295d_16    conda-forge
	glib                      2.58.3          py38h6f030ca_1002    conda-forge
	graphite2                 1.3.13            hf484d3e_1000    conda-forge
	gsl                       2.5                  h294904e_1    conda-forge
	gxx_impl_linux-64         7.3.0                hdf63c60_4    conda-forge
	gxx_linux-64              7.3.0               h553295d_16    conda-forge
	harfbuzz                  2.4.0                h9f30f68_3    conda-forge
	icu                       64.2                 he1b5a44_1    conda-forge
	importlib_metadata        1.4.0                    py38_0    conda-forge
	ipykernel                 5.1.3            py38h5ca1d4c_0    conda-forge
	ipython                   7.11.1           py38h5ca1d4c_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	isort                     4.3.21                   py38_0    conda-forge
	jedi                      0.15.2                   py38_0    conda-forge
	jinja2                    2.10.3                     py_0    conda-forge
	jpeg                      9c                h14c3975_1001    conda-forge
	json5                     0.8.5                      py_0    conda-forge
	jsonschema                3.2.0                    py38_0    conda-forge
	jupyter-lsp               0.7.0b0                  pypi_0    pypi
	jupyter_client            5.3.4                    py38_1    conda-forge
	jupyter_core              4.6.1                    py38_0    conda-forge
	jupyterlab                1.2.6                      py_0    conda-forge
	jupyterlab_server         1.0.6                      py_0    conda-forge
	krb5                      1.16.4               h2fd8d38_0    conda-forge
	lazy-object-proxy         1.4.3            py38h516909a_1    conda-forge
	ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
	libblas                   3.8.0               14_openblas    conda-forge
	libcblas                  3.8.0               14_openblas    conda-forge
	libcurl                   7.65.3               hda55be3_0    conda-forge
	libedit                   3.1.20170329      hf8c457e_1001    conda-forge
	libffi                    3.2.1             he1b5a44_1006    conda-forge
	libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
	libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
	libgomp                   9.2.0                h24d8f2e_2    conda-forge
	libiconv                  1.15              h516909a_1005    conda-forge
	liblapack                 3.8.0               14_openblas    conda-forge
	libopenblas               0.3.7                h5ec1e0e_6    conda-forge
	libpng                    1.6.37               hed695b0_0    conda-forge
	libsodium                 1.0.17               h516909a_0    conda-forge
	libssh2                   1.8.2                h22169c7_2    conda-forge
	libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
	libtiff                   4.1.0                hc3755c2_3    conda-forge
	libuuid                   2.32.1            h14c3975_1000    conda-forge
	libuv                     1.34.0               h516909a_0    conda-forge
	libxcb                    1.13              h14c3975_1002    conda-forge
	libxml2                   2.9.10               hee79883_0    conda-forge
	lz4-c                     1.8.3             he1b5a44_1001    conda-forge
	make                      4.2.1             h14c3975_2004    conda-forge
	markupsafe                1.1.1            py38h516909a_0    conda-forge
	mccabe                    0.6.1                    pypi_0    pypi
	mistune                   0.8.4           py38h516909a_1000    conda-forge
	more-itertools            8.1.0                      py_0    conda-forge
	nbconvert                 5.6.1                    py38_0    conda-forge
	nbformat                  5.0.4                      py_0    conda-forge
	ncurses                   6.1               hf484d3e_1002    conda-forge
	nodejs                    13.7.0               h10a4023_0    conda-forge
	notebook                  6.0.3                    py38_0    conda-forge
	openssl                   1.1.1d               h516909a_0    conda-forge
	pandoc                    2.9.1.1                       0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	pango                     1.42.4               ha030887_1    conda-forge
	parso                     0.5.2                      py_0    conda-forge
	pcre                      8.43                 he1b5a44_0    conda-forge
	pexpect                   4.8.0                    py38_0    conda-forge
	pickleshare               0.7.5                 py38_1000    conda-forge
	pip                       20.0.2                   py38_0    conda-forge
	pixman                    0.38.0            h516909a_1003    conda-forge
	pluggy                    0.13.1                   py38_0    conda-forge
	prometheus_client         0.7.1                      py_0    conda-forge
	prompt_toolkit            3.0.2                      py_0    conda-forge
	pthread-stubs             0.4               h14c3975_1001    conda-forge
	ptyprocess                0.6.0                   py_1001    conda-forge
	pycodestyle               2.5.0                      py_0    conda-forge
	pydocstyle                5.0.2                      py_0    conda-forge
	pyflakes                  2.1.1                      py_0    conda-forge
	pygments                  2.5.2                      py_0    conda-forge
	pylint                    2.4.4                    py38_0    conda-forge
	pyrsistent                0.15.7           py38h516909a_0    conda-forge
	python                    3.8.1                h357f687_1    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python-jsonrpc-server     0.3.4                      py_0    conda-forge
	python-language-server    0.31.7                   py38_0    conda-forge
	pyzmq                     18.1.1           py38h1768529_0    conda-forge
	r-askpass                 1.1               r36hcdcec82_1    conda-forge
	r-assertthat              0.2.1             r36h6115d3f_1    conda-forge
	r-backports               1.1.5             r36hcdcec82_0    conda-forge
	r-base                    3.6.2                h3a67422_0    conda-forge
	r-base64enc               0.1_3           r36hcdcec82_1003    conda-forge
	r-callr                   3.4.1             r36h6115d3f_0    conda-forge
	r-cli                     2.0.1             r36h6115d3f_0    conda-forge
	r-clipr                   0.7.0             r36h6115d3f_0    conda-forge
	r-codetools               0.2_16          r36h6115d3f_1001    conda-forge
	r-collections             0.2.3             r36hcdcec82_0    conda-forge
	r-crayon                  1.3.4           r36h6115d3f_1002    conda-forge
	r-curl                    4.3               r36hcdcec82_0    conda-forge
	r-cyclocomp               1.1.0           r36h6115d3f_1003    conda-forge
	r-desc                    1.2.0           r36h6115d3f_1002    conda-forge
	r-digest                  0.6.23            r36h0357c0b_0    conda-forge
	r-ellipsis                0.3.0             r36hcdcec82_0    conda-forge
	r-evaluate                0.14              r36h6115d3f_1    conda-forge
	r-fansi                   0.4.1             r36hcdcec82_0    conda-forge
	r-glue                    1.3.1             r36hcdcec82_1    conda-forge
	r-highr                   0.8               r36h6115d3f_1    conda-forge
	r-hms                     0.5.3             r36h6115d3f_0    conda-forge
	r-htmltools               0.4.0             r36h0357c0b_0    conda-forge
	r-httr                    1.4.1             r36h6115d3f_1    conda-forge
	r-jsonlite                1.6             r36hcdcec82_1001    conda-forge
	r-knitr                   1.27              r36h6115d3f_0    conda-forge
	r-languageserver          0.3.3             r36hcdcec82_0    conda-forge
	r-lazyeval                0.2.2             r36hcdcec82_1    conda-forge
	r-lintr                   2.0.0             r36h6115d3f_0    conda-forge
	r-magrittr                1.5             r36h6115d3f_1002    conda-forge
	r-markdown                1.1               r36hcdcec82_0    conda-forge
	r-mime                    0.8               r36hcdcec82_0    conda-forge
	r-openssl                 1.4.1             r36h9c8475f_0    conda-forge
	r-pillar                  1.4.3             r36h6115d3f_0    conda-forge
	r-pkgbuild                1.0.6             r36h6115d3f_0    conda-forge
	r-pkgconfig               2.0.3             r36h6115d3f_0    conda-forge
	r-pkgload                 1.0.2           r36h0357c0b_1001    conda-forge
	r-praise                  1.0.0           r36h6115d3f_1003    conda-forge
	r-prettyunits             1.1.1             r36h6115d3f_0    conda-forge
	r-processx                3.4.1             r36hcdcec82_0    conda-forge
	r-ps                      1.3.0           r36hcdcec82_1001    conda-forge
	r-purrr                   0.3.3             r36hcdcec82_0    conda-forge
	r-r6                      2.4.1             r36h6115d3f_0    conda-forge
	r-rcpp                    1.0.3             r36h0357c0b_0    conda-forge
	r-readr                   1.3.1           r36h0357c0b_1002    conda-forge
	r-rematch2                2.1.0             r36h6115d3f_0    conda-forge
	r-remotes                 2.1.0             r36h6115d3f_1    conda-forge
	r-repr                    1.0.2             r36h6115d3f_0    conda-forge
	r-rex                     1.1.2           r36h6115d3f_1001    conda-forge
	r-rlang                   0.4.3             r36hcdcec82_0    conda-forge
	r-rprojroot               1.3_2           r36h6115d3f_1002    conda-forge
	r-rstudioapi              0.10              r36h6115d3f_2    conda-forge
	r-stringdist              0.9.5.5           r36hcdcec82_0    conda-forge
	r-stringi                 1.4.5             r36h0e574ca_0    conda-forge
	r-stringr                 1.4.0             r36h6115d3f_1    conda-forge
	r-styler                  1.2.0             r36h6115d3f_0    conda-forge
	r-sys                     3.3               r36hcdcec82_0    conda-forge
	r-testthat                2.3.1             r36h0357c0b_0    conda-forge
	r-tibble                  2.1.3             r36hcdcec82_1    conda-forge
	r-utf8                    1.1.4           r36hcdcec82_1001    conda-forge
	r-vctrs                   0.2.2             r36hcdcec82_0    conda-forge
	r-withr                   2.1.2           r36h6115d3f_1001    conda-forge
	r-xfun                    0.12              r36h6115d3f_0    conda-forge
	r-xml2                    1.2.2             r36h0357c0b_0    conda-forge
	r-xmlparsedata            1.0.3             r36h6115d3f_0    conda-forge
	r-xptr                    1.1.2             r36hcdcec82_0    conda-forge
	r-yaml                    2.2.0           r36hcdcec82_1002    conda-forge
	r-zeallot                 0.1.0           r36h6115d3f_1001    conda-forge
	readline                  8.0                  hf8c457e_0    conda-forge
	rope                      0.16.0                     py_0    conda-forge
	sed                       4.7               h1bed415_1000    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                45.1.0                   py38_0    conda-forge
	six                       1.14.0                   py38_0    conda-forge
	snowballstemmer           2.0.0                      py_0    conda-forge
	sqlite                    3.30.1               hcee41ef_0    conda-forge
	terminado                 0.8.3                    py38_0    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	tk                        8.6.10               hed695b0_0    conda-forge
	tktable                   2.10                 h555a92e_3    conda-forge
	tornado                   6.0.3            py38h516909a_0    conda-forge
	traitlets                 4.3.3                    py38_0    conda-forge
	ujson                     1.35                     pypi_0    pypi
	wcwidth                   0.1.8                      py_0    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.33.6                   py38_0    conda-forge
	wrapt                     1.11.2           py38h516909a_0    conda-forge
	xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
	xorg-libice               1.0.10               h516909a_0    conda-forge
	xorg-libsm                1.2.3             h84519dc_1000    conda-forge
	xorg-libx11               1.6.9                h516909a_0    conda-forge
	xorg-libxau               1.0.9                h14c3975_0    conda-forge
	xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
	xorg-libxext              1.3.4                h516909a_0    conda-forge
	xorg-libxrender           0.9.10            h516909a_1002    conda-forge
	xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
	xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
	xorg-xproto               7.0.31            h14c3975_1007    conda-forge
	xz                        5.2.4             h14c3975_1001    conda-forge
	yapf                      0.29.0                   pypi_0    pypi
	zeromq                    4.3.2                he1b5a44_2    conda-forge
	zipp                      2.0.0                      py_2    conda-forge
	zlib                      1.2.11            h516909a_1006    conda-forge
	zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

<details><summary>Command Line Output</summary>

```
[D 17:59:34.127 LabApp] Searching ['/home/ian/anaconda3/envs/jlab-test/etc', '/home/ian/.jupyter', '/home/ian/anaconda3/envs/jlab-test/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files                               
[D 17:59:34.127 LabApp] Looking for jupyter_config in /etc/jupyter                                                                                                                                                                            
[D 17:59:34.127 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter                                                                                                                                                                  
[D 17:59:34.127 LabApp] Looking for jupyter_config in /home/ian/anaconda3/envs/jlab-test/etc/jupyter                                                                                                                                          
[D 17:59:34.127 LabApp] Looking for jupyter_config in /home/ian/.jupyter                                                                                                                                                                      
[D 17:59:34.127 LabApp] Looking for jupyter_config in /home/ian/anaconda3/envs/jlab-test/etc                                                                                                                                                  
[D 17:59:34.128 LabApp] Looking for jupyter_notebook_config in /etc/jupyter                                                                                                                                                                   
[D 17:59:34.128 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter                                                                                                                                                         
[D 17:59:34.128 LabApp] Looking for jupyter_notebook_config in /home/ian/anaconda3/envs/jlab-test/etc/jupyter                                                                                                                                 
[D 17:59:34.128 LabApp] Looking for jupyter_notebook_config in /home/ian/.jupyter                                                                                                                                                             
[D 17:59:34.128 LabApp] Loaded config file: /home/ian/.jupyter/jupyter_notebook_config.py                                                                                                                                                     
[D 17:59:34.128 LabApp] Looking for jupyter_notebook_config in /home/ian/anaconda3/envs/jlab-test/etc                                                                                                                                         
[D 17:59:34.129 LabApp] Raising open file limit: soft 1024->4096; hard 524288->524288                                                                                                                                                         
[D 17:59:34.131 LabApp] Paths used for configuration of jupyter_notebook_config:                                                                                                                                                              
        /etc/jupyter/jupyter_notebook_config.json                                                                                                                                                                                             
[D 17:59:34.132 LabApp] Paths used for configuration of jupyter_notebook_config:                                                                                                                                                              
        /usr/local/etc/jupyter/jupyter_notebook_config.json                                                                                                                                                                                   
[D 17:59:34.132 LabApp] Paths used for configuration of jupyter_notebook_config:                                                                                                                                                              
        /home/ian/anaconda3/envs/jlab-test/etc/jupyter/jupyter_notebook_config.d/jupyter-lsp-serverextension.json                                                                                                                             
        /home/ian/anaconda3/envs/jlab-test/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json                                                                                                                                              
        /home/ian/anaconda3/envs/jlab-test/etc/jupyter/jupyter_notebook_config.json                                                                                                                                                           
[D 17:59:34.132 LabApp] Paths used for configuration of jupyter_notebook_config:                                                                                                                                                              
        /home/ian/.jupyter/jupyter_notebook_config.json                                                                                                                                                                                       
[I 17:59:34.277 LabApp] The port 8888 is already in use, trying another port.                                                                                                                                                                 
[D 17:59:34.422 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/bash-language-server/bin/main.js                                                                                                                     
[D 17:59:34.422 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/bash-language-server/bin/main.js                                                                                               
[D 17:59:34.422 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/bash-language-server/bin/main.js                                                                                                                     
[D 17:59:34.423 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/bash-language-server/bin/main.js                                                                                                                         
[W 17:59:34.423 LabApp] Failed to fetch commands from language server spec finder`bash-language-server`:                                                                                                                                      
    expected str, bytes or os.PathLike object, not tuple                                                                                                                                                                                      
[D 17:59:34.425 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/dockerfile-language-server-nodejs/lib/server.js                                                                                                      
[D 17:59:34.425 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/dockerfile-language-server-nodejs/lib/server.js                                                                                
[D 17:59:34.425 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/dockerfile-language-server-nodejs/lib/server.js                                                                                                      
[D 17:59:34.425 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/dockerfile-language-server-nodejs/lib/server.js                                                                                                          
[W 17:59:34.425 LabApp] Failed to fetch commands from language server spec finder`dockerfile-language-server-nodejs`:                                                                                                                         
    expected str, bytes or os.PathLike object, not tuple                                                                                                                                                                                      
[D 17:59:34.427 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js                                                                                        
[D 17:59:34.427 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js                                                                  
[D 17:59:34.428 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js                                                                                        
[D 17:59:34.428 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js                                                                                            
[W 17:59:34.428 LabApp] Failed to fetch commands from language server spec finder`javascript-typescript-langserver`:                                                                                                                          
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.449 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/unified-language-server/src/server.js
[D 17:59:34.449 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/unified-language-server/src/server.js
[D 17:59:34.449 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/unified-language-server/src/server.js
[D 17:59:34.449 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/unified-language-server/src/server.js
[W 17:59:34.449 LabApp] Failed to fetch commands from language server spec finder`unified-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.451 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 17:59:34.451 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 17:59:34.451 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 17:59:34.451 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[W 17:59:34.451 LabApp] Failed to fetch commands from language server spec finder`vscode-css-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.453 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 17:59:34.453 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 17:59:34.453 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 17:59:34.453 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[W 17:59:34.453 LabApp] Failed to fetch commands from language server spec finder`vscode-html-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.455 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 17:59:34.455 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 17:59:34.455 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 17:59:34.455 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[W 17:59:34.455 LabApp] Failed to fetch commands from language server spec finder`vscode-json-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.457 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/etc/node_modules/yaml-language-server/bin/yaml-language-server
[D 17:59:34.457 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/share/jupyter/lab/staging/node_modules/yaml-language-server/bin/yaml-language-server
[D 17:59:34.457 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/lib/node_modules/yaml-language-server/bin/yaml-language-server
[D 17:59:34.457 LabApp] Checking for /home/ian/anaconda3/envs/jlab-test/node_modules/yaml-language-server/bin/yaml-language-server
[W 17:59:34.458 LabApp] Failed to fetch commands from language server spec finder`yaml-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[D 17:59:34.461 LabApp] [lsp] rootUri will be file:///home/ian/anaconda3/envs/jlab-test/etc
[D 17:59:34.461 LabApp] [lsp] virtualDocumentsUri will be file:///home/ian/anaconda3/envs/jlab-test/etc/.virtual_documents
[D 17:59:34.462 LabApp] [lsp] The following Language Servers will be available: {
....
}
```
</details>

**Comment by krassowski** [comment] 2020-01-26 20:52
Thank you for the detailed information! I could not reproduce, but a few hints I can give:

- nodejs needs to be installed before the extension (otherwise it would not work). If it worked, you likely have a nodejs installed somewhere in the system.... So it would be:
   ```
   conda install -c conda-forge nodejs
   jupyter labextension install @krassowski/jupyterlab-lsp
   ```
    But I would double-check `which`  nodejs you are really using.
- Another user found out that [downgrading nodejs to 10.13 helped them](https://github.com/krassowski/jupyterlab-lsp/issues/123#issuecomment-570803804) - it might help you as well

Either way, please do let us know what you find. Sorry, I could not be more helpful - I'm not a conda person (but I can help if you run into problems using [pyvenv](https://github.com/pyenv/pyenv)/[pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv)).

**Comment by IanQS** [comment] 2020-01-26 23:17
> Thank you for the detailed information! I could not reproduce, but a few hints I can give:

Can you list the exact commands you ran to go from initial conda env -> running lsp server? 

I ran 

```
conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab nodejs  # Note the nodejs
conda activate jlab-test
pip install --pre jupyter-lsp
jupyter labextension install @krassowski/jupyterlab-lsp
conda install -c conda-forge python-language-server r-languageserver
jupyter lab
```

And I still saw the error 

--- 

>  user found out that downgrading nodejs to 10.13 helped them - it might help you as well

Ahh, didn't help. 

--- 

> nodejs needs to be installed before the extension

Might want to explicitly list that in the install guide

**Comment by krassowski** [comment] 2021-01-09 00:48
Closing this issue as NodeJS is no longer required to install this extension for JupyterLab 3.0.

**Closed by krassowski** 2021-01-09 00:48 UTC
