### ISSUE TITLE
Automatic Completion not working

### ISSUE THREAD

**Issue by dddping** [krassowski/jupyterlab-lsp#286] opened 2020-06-24 12:47 UTC
## Description
'.' (dot) in Python don't automatically trigger completion.

## Reproduce

1. Launch a new python3 notebook
2. Type `import pandas as pd` in first cell, then ctrl-Enter
3. Type `pd.` in second cell....nothing happen

## Expected behavior
Not sure whether I have the correct setting. I also paste the list output of labextension and serverextension.
![image](https://user-images.githubusercontent.com/47309306/85558456-53a7b380-b65b-11ea-981d-18f5323ef616.png)
![image](https://user-images.githubusercontent.com/47309306/85558550-6b7f3780-b65b-11ea-806e-a571ca5205a1.png)
![image](https://user-images.githubusercontent.com/47309306/85558773-a71a0180-b65b-11ea-85f5-8e89a51673c6.png)

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Required: installed server extensions</summary>
<pre>
config dir: C:\Users\...\.jupyter
    jupyter_nbextensions_configurator enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
config dir: d:\...\jupyter
    jupyter_lsp enabled
    - Validating...
      jupyter_lsp 0.8.0 ok
    jupyterlab-snippets enabled
    - Validating...
      jupyterlab-snippets 0.3.2 ok
    jupyterlab enabled
    - Validating...
      jupyterlab 2.1.5 ok

</pre>

</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v2.1.5
Known labextensions:
   app dir: d:\...\jupyter\lab
        @krassowski/jupyterlab-lsp v1.0.0 enabled  ok
        jupyterlab-snippets v0.3.2 enabled  ok
</pre>

</details>

<details><summary>Troubleshoot Output</summary>
<pre>
INFO: Could not find files for the given pattern(s).
$PATH:
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\Git\cmd
        C:\Program Files\TortoiseGit\bin
        D:\AppInstall\nodejs\
        C:\Users\...\AppData\Local\Microsoft\WindowsApps
        C:\Users\...\AppData\Roaming\Amazon
        C:\Users\...\AppData\Roaming\npm

sys.path:
        d:\...\dev_pycpy3\Scripts\jupyter-troubleshoot.EXE
        C:\Program Files\Python38\python38.zip
        C:\Program Files\Python38\DLLs
        C:\Program Files\Python38\lib
        C:\Program Files\Python38
        d:\...\dev_pycpy3
        d:\...\dev_pycpy3\lib\site-packages
        d:\...\dev_pycpy3\lib\site-packages\win32
        d:\...\dev_pycpy3\lib\site-packages\win32\lib
        d:\...\dev_pycpy3\lib\site-packages\Pythonwin

sys.executable:
        d:\...\dev_pycpy3\scripts\python.exe

sys.version:
        3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

pip list:
        Package                           Version
        --------------------------------- ------------
        -ip                               20.0.2
        astroid                           2.4.2
        atomicwrites                      1.3.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by dddping** [comment] 2020-06-24 12:54
Remark
1. jupyterlab is installed in virtualenv
2. jupyterlab-snippets and jupyterlab-toc are working fine

**Comment by jamiesheng** [comment] 2020-06-30 19:01
Mine doesn't work as well TAT

**Comment by krassowski** [comment] 2020-06-30 22:35
Thank you for trying out this extension and your feedback!

@dddping Can you see the popover on the status bar with the statuses of the language servers? Do you have a python language server installed (I do not see it in your logs)? Did you perform step six of this installation instruction: https://github.com/krassowski/jupyterlab-lsp#installation?

@jamiesheng Please use [this template](https://github.com/krassowski/jupyterlab-lsp/issues/new?template=bug_report.md) to provide the information which is needed to rule out configuration issue and tell us what might be the cause.

To both of you - do other LSP functions work for you?

**Comment by ryanni666** [comment] 2020-07-06 15:39
![image](https://user-images.githubusercontent.com/67346146/86611817-3806ac00-bf7d-11ea-8e5d-29b9bb7de8cd.png)
I follow your steps, but it still doesn't work. Thanks!

**Comment by krassowski** [comment] 2020-07-19 22:14
I will be closing this for now, as according to our cheks the completion works fine with JupyterLab 2.1. It is likely that the python-language-server was not installed which prevented this functionality from working.

Please re-open this issue, providing full details if you see this problem again (after ensuring a complete installation).

**Closed by krassowski** 2020-07-19 22:14 UTC
